## Univariate Feature Selection

In [3]:
# Feature extraction with univariate statistical test (Chi-squared for classification)
from pandas import read_csv
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

# Load data
filename = '/home/aman/Downloads/Learning/Data science/Feature engineering/pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'ped1', 'age', 'class']
dataframe = read_csv(filename, names=names)
array = dataframe.values
X = array[:, 0:8]
Y = array[:,8]

# Feature extraction
test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(X, Y)

# Summarize scores
set_printoptions(precision=3)
print(fit.scores_)
feature = fit.transform(X)


# For regression f_regression, mutual_info_regression
# For classification: chi2, f_classif, mutual_info_classif

[ 111.52  1411.887   17.605   53.108 2175.565  127.669    5.393  181.304]


In [4]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'ped1', 'age', 'class']

## Recrusive feature elimination

In [9]:
# Feature Extraction with RFE
from pandas import read_csv
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression


# Load data
filename = '/home/aman/Downloads/Learning/Data science/Feature engineering/pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'ped1', 'age', 'class']
dataframe = read_csv(filename, names=names)
X = array[:, 0:8]
Y = array[:,8]

# Feature extraction
model= LogisticRegression(max_iter=400)
rfe = RFE(model, 3)
fit = rfe.fit(X,Y)

/home/aman/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:67: FutureWarning: Pass n_features_to_select=3 as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


In [10]:
# NUm Features
fit.n_features_

3

In [13]:
# Selected Features
fit.support_

array([ True, False, False, False, False,  True,  True, False])

In [14]:
# Feature Ranking
fit.ranking_

array([1, 2, 4, 6, 5, 1, 1, 3])

In [15]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'ped1', 'age', 'class']

## Feature Important using Decission Tree

In [23]:
# Feature Extraction with RFE
from pandas import read_csv
from sklearn.tree import DecisionTreeClassifier

# Load data
filename = '/home/aman/Downloads/Learning/Data science/Feature engineering/pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'ped1', 'age', 'class']
dataframe = read_csv(filename, names=names)
X = array[:, 0:8]
Y = array[:,8]

# Feature extraction
model= DecisionTreeClassifier()
model.fit(X,Y)
print(model.feature_importances_)

[0.061 0.312 0.086 0.019 0.036 0.236 0.13  0.12 ]
